# replace .war with .jar or .ear if needed
name: Whitesource Prioritize Java with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean install -DskipTests=true
      - name: WhiteSource Unified Agent Scan
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WS_APIKEY: f77338a45dcb46e9898e4090f24e9f7aa9fcebcadd91453ebd8ce9b46339d804
          WS_USERKEY: 9b5ddaeaa0fe4a45941e403512085925505bb3f27761450c832ac89496f7ffd2
          WS_WSS_URL: https://saas.whitesourcesoftware.com/agent
          WS_PRODUCTNAME: Mend-Tim
          WS_PROJECTNAME: EasyBuggy_Prioritize
          WS_ENABLEIMPACTANALYSIS: true
          WS_REQUIREKNOWNSHA1: false
          WS_RESOLVEALLDEPENDENCIES: false
          WS_MAVEN_RESOLVEDEPENDENCIES: true
          WS_MAVEN_AGGREGATEMODULES: true
          WS_FILESYSTEMSCAN: false
          WS_GENERATEPROJECTDETAILSJSON: true
        run: |
          curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
          echo Unified Agent downloaded successfully
          WARFILE=$(find ./ -type f -wholename "*/target/*.war")
          echo $WARFILE will be added to appPath
          java -jar wss-unified-agent.jar -appPath $WARFILE -d ./
